/*
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CmcCounterStandaloneSetup extends CmcCounterStandaloneSetupGenerated {

	public static void doSetup() {
		new CmcCounterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
