/* Copyright (c) 2022 Massimiliano "Maxi" Zattera */

/*
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CmcCounterRuntimeModule extends AbstractCmcCounterRuntimeModule {
}
