/*
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count.parser.antlr;

import com.google.inject.Inject;
import io.github.mzattera.v4j.cmc.count.parser.antlr.internal.InternalCmcCounterParser;
import io.github.mzattera.v4j.cmc.count.services.CmcCounterGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CmcCounterParser extends AbstractAntlrParser {

	@Inject
	private CmcCounterGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_COMMENT");
	}
	

	@Override
	protected InternalCmcCounterParser createParser(XtextTokenStream stream) {
		return new InternalCmcCounterParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Grammar";
	}

	public CmcCounterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CmcCounterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
