/*
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCmcCounterScopeProvider extends DelegatingScopeProvider {
}
