/* Copyright (c) 2022 Massimiliano "Maxi" Zattera */

/*
 * generated by Xtext 2.28.0
 */
package io.github.mzattera.v4j.cmc.count.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCmcCounterScopeProvider extends DelegatingScopeProvider {
}
