/* Copyright (c) 2022 Massimiliano "Maxi" Zattera */

/**
 * generated by Xtext 2.28.0
 */
package io.github.mzattera.v4j.cmc.count.cmcCounter;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterFactory
 * @model kind="package"
 * @generated
 */
public interface CmcCounterPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cmcCounter";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.github.io/mzattera/v4j/cmc/count/CmcCounter";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cmcCounter";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CmcCounterPackage eINSTANCE = io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl.init();

  /**
   * The meta object id for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.GrammarImpl <em>Grammar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.GrammarImpl
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getGrammar()
   * @generated
   */
  int GRAMMAR = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAMMAR__RULES = 0;

  /**
   * The number of structural features of the '<em>Grammar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAMMAR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleOrTextImpl <em>Rule Or Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleOrTextImpl
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getRuleOrText()
   * @generated
   */
  int RULE_OR_TEXT = 1;

  /**
   * The feature id for the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_OR_TEXT__RULE = 0;

  /**
   * The feature id for the '<em><b>Txt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_OR_TEXT__TXT = 1;

  /**
   * The number of structural features of the '<em>Rule Or Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_OR_TEXT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleImpl
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getRule()
   * @generated
   */
  int RULE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Expansions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__EXPANSIONS = 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.ExpansionImpl <em>Expansion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.ExpansionImpl
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getExpansion()
   * @generated
   */
  int EXPANSION = 3;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPANSION__COUNT = 0;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPANSION__FREQUENCY = 1;

  /**
   * The feature id for the '<em><b>Cumulated Freq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPANSION__CUMULATED_FREQ = 2;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPANSION__RULES = 3;

  /**
   * The number of structural features of the '<em>Expansion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPANSION_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Grammar <em>Grammar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grammar</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Grammar
   * @generated
   */
  EClass getGrammar();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Grammar#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Grammar#getRules()
   * @see #getGrammar()
   * @generated
   */
  EReference getGrammar_Rules();

  /**
   * Returns the meta object for class '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText <em>Rule Or Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Or Text</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText
   * @generated
   */
  EClass getRuleOrText();

  /**
   * Returns the meta object for the reference '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rule</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getRule()
   * @see #getRuleOrText()
   * @generated
   */
  EReference getRuleOrText_Rule();

  /**
   * Returns the meta object for the attribute '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getTxt <em>Txt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Txt</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getTxt()
   * @see #getRuleOrText()
   * @generated
   */
  EAttribute getRuleOrText_Txt();

  /**
   * Returns the meta object for class '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Rule#getExpansions <em>Expansions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expansions</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Rule#getExpansions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Expansions();

  /**
   * Returns the meta object for class '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion <em>Expansion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expansion</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion
   * @generated
   */
  EClass getExpansion();

  /**
   * Returns the meta object for the attribute '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCount()
   * @see #getExpansion()
   * @generated
   */
  EAttribute getExpansion_Count();

  /**
   * Returns the meta object for the attribute '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getFrequency()
   * @see #getExpansion()
   * @generated
   */
  EAttribute getExpansion_Frequency();

  /**
   * Returns the meta object for the attribute '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCumulatedFreq <em>Cumulated Freq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumulated Freq</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCumulatedFreq()
   * @see #getExpansion()
   * @generated
   */
  EAttribute getExpansion_CumulatedFreq();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getRules()
   * @see #getExpansion()
   * @generated
   */
  EReference getExpansion_Rules();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CmcCounterFactory getCmcCounterFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.GrammarImpl <em>Grammar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.GrammarImpl
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getGrammar()
     * @generated
     */
    EClass GRAMMAR = eINSTANCE.getGrammar();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAMMAR__RULES = eINSTANCE.getGrammar_Rules();

    /**
     * The meta object literal for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleOrTextImpl <em>Rule Or Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleOrTextImpl
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getRuleOrText()
     * @generated
     */
    EClass RULE_OR_TEXT = eINSTANCE.getRuleOrText();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_OR_TEXT__RULE = eINSTANCE.getRuleOrText_Rule();

    /**
     * The meta object literal for the '<em><b>Txt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_OR_TEXT__TXT = eINSTANCE.getRuleOrText_Txt();

    /**
     * The meta object literal for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.RuleImpl
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Expansions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__EXPANSIONS = eINSTANCE.getRule_Expansions();

    /**
     * The meta object literal for the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.impl.ExpansionImpl <em>Expansion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.ExpansionImpl
     * @see io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterPackageImpl#getExpansion()
     * @generated
     */
    EClass EXPANSION = eINSTANCE.getExpansion();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPANSION__COUNT = eINSTANCE.getExpansion_Count();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPANSION__FREQUENCY = eINSTANCE.getExpansion_Frequency();

    /**
     * The meta object literal for the '<em><b>Cumulated Freq</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPANSION__CUMULATED_FREQ = eINSTANCE.getExpansion_CumulatedFreq();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPANSION__RULES = eINSTANCE.getExpansion_Rules();

  }

} //CmcCounterPackage
