/**
 * generated by Xtext 2.28.0
 */
package io.github.mzattera.v4j.cmc.count.cmcCounter;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage
 * @generated
 */
public interface CmcCounterFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CmcCounterFactory eINSTANCE = io.github.mzattera.v4j.cmc.count.cmcCounter.impl.CmcCounterFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Grammar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Grammar</em>'.
   * @generated
   */
  Grammar createGrammar();

  /**
   * Returns a new object of class '<em>Rule Or Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Or Text</em>'.
   * @generated
   */
  RuleOrText createRuleOrText();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Expansion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expansion</em>'.
   * @generated
   */
  Expansion createExpansion();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CmcCounterPackage getCmcCounterPackage();

} //CmcCounterFactory
