/**
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count.cmcCounter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expansion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCount <em>Count</em>}</li>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getFrequency <em>Frequency</em>}</li>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCumulatedFreq <em>Cumulated Freq</em>}</li>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getExpansion()
 * @model
 * @generated
 */
public interface Expansion extends EObject
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(double)
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getExpansion_Count()
   * @model
   * @generated
   */
  double getCount();

  /**
   * Sets the value of the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(double value);

  /**
   * Returns the value of the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frequency</em>' attribute.
   * @see #setFrequency(double)
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getExpansion_Frequency()
   * @model
   * @generated
   */
  double getFrequency();

  /**
   * Sets the value of the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getFrequency <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frequency</em>' attribute.
   * @see #getFrequency()
   * @generated
   */
  void setFrequency(double value);

  /**
   * Returns the value of the '<em><b>Cumulated Freq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumulated Freq</em>' attribute.
   * @see #setCumulatedFreq(double)
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getExpansion_CumulatedFreq()
   * @model
   * @generated
   */
  double getCumulatedFreq();

  /**
   * Sets the value of the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.Expansion#getCumulatedFreq <em>Cumulated Freq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumulated Freq</em>' attribute.
   * @see #getCumulatedFreq()
   * @generated
   */
  void setCumulatedFreq(double value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getExpansion_Rules()
   * @model containment="true"
   * @generated
   */
  EList<RuleOrText> getRules();

} // Expansion
