/**
 * generated by Xtext 2.25.0
 */
package io.github.mzattera.v4j.cmc.count.cmcCounter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Or Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getRule <em>Rule</em>}</li>
 *   <li>{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getTxt <em>Txt</em>}</li>
 * </ul>
 *
 * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getRuleOrText()
 * @model
 * @generated
 */
public interface RuleOrText extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' reference.
   * @see #setRule(Rule)
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getRuleOrText_Rule()
   * @model
   * @generated
   */
  Rule getRule();

  /**
   * Sets the value of the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getRule <em>Rule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' reference.
   * @see #getRule()
   * @generated
   */
  void setRule(Rule value);

  /**
   * Returns the value of the '<em><b>Txt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Txt</em>' attribute.
   * @see #setTxt(String)
   * @see io.github.mzattera.v4j.cmc.count.cmcCounter.CmcCounterPackage#getRuleOrText_Txt()
   * @model
   * @generated
   */
  String getTxt();

  /**
   * Sets the value of the '{@link io.github.mzattera.v4j.cmc.count.cmcCounter.RuleOrText#getTxt <em>Txt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Txt</em>' attribute.
   * @see #getTxt()
   * @generated
   */
  void setTxt(String value);

} // RuleOrText
